### ISSUE TITLE
IllegalState: OPERATOR fallback already mapped to DEFAULT_BRACES

### ISSUE THREAD

**Issue by maunzCache** [java-prolog-connectivity/logtalk-intellij#13]
Version: 1.0.14

```
java.lang.IllegalStateException: TextAttributeKey(name:'OPERATOR', fallbackAttributeKey:'DEFAULT_CONSTANT')  was already registered with the other fallback attribute key: DEFAULT_BRACES
	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:216)
	at com.intellij.openapi.editor.colors.TextAttributesKey.lambda$getOrCreate$4(TextAttributesKey.java:202)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932)
	at com.intellij.openapi.editor.colors.TextAttributesKey.getOrCreate(TextAttributesKey.java:202)
	at com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey(TextAttributesKey.java:189)
	at org.logtalk.intellij.editor.LogtalkSyntaxHighlighter.<clinit>(LogtalkSyntaxHighlighter.java:22)
	at org.logtalk.intellij.editor.LogtalkSyntaxHighlighterFactory.getSyntaxHighlighter(LogtalkSyntaxHighlighterFactory.java:15)
	at com.intellij.openapi.fileTypes.SyntaxHighlighterFactory.getSyntaxHighlighter(SyntaxHighlighterFactory.java:39)
	at org.jetbrains.plugins.ruby.ruby.lang.highlighter.RubyEditorHighlighter.<init>(RubyEditorHighlighter.java:45)
	at org.jetbrains.plugins.ruby.ruby.lang.highlighter.RubyEditorHighlighterProvider.getEditorHighlighter(RubyEditorHighlighterProvider.java:18)
	at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:78)
	at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:107)
	at com.intellij.diff.util.DiffUtil.createEditorHighlighter(DiffUtil.java:166)
	at com.intellij.diff.util.DiffUtil.setEditorHighlighter(DiffUtil.java:181)
	at com.intellij.diff.util.DiffUtil.configureEditor(DiffUtil.java:242)
	at com.intellij.diff.tools.holders.TextEditorHolder.create(TextEditorHolder.java:94)
	at com.intellij.diff.tools.holders.TextEditorHolder$TextEditorHolderFactory.create(TextEditorHolder.java:104)
	at com.intellij.diff.tools.holders.TextEditorHolder$TextEditorHolderFactory.create(TextEditorHolder.java:98)
	at com.intellij.diff.tools.util.side.OnesideDiffViewer.createEditorHolder(OnesideDiffViewer.java:79)
	at com.intellij.diff.tools.util.side.OnesideTextDiffViewer.createEditorHolder(OnesideTextDiffViewer.java:68)
	at com.intellij.diff.tools.util.side.OnesideTextDiffViewer.createEditorHolder(OnesideTextDiffViewer.java:33)
	at com.intellij.diff.tools.util.side.OnesideDiffViewer.<init>(OnesideDiffViewer.java:51)
	at com.intellij.diff.tools.util.side.OnesideTextDiffViewer.<init>(OnesideTextDiffViewer.java:39)
	at com.intellij.diff.tools.simple.SimpleOnesideDiffViewer.<init>(SimpleOnesideDiffViewer.java:57)
	at com.intellij.diff.tools.simple.SimpleDiffTool.createComponent(SimpleDiffTool.java:29)
	at com.intellij.diff.impl.DiffRequestProcessor.createState(DiffRequestProcessor.java:256)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$doApplyRequest$1(DiffRequestProcessor.java:329)
	at com.intellij.diff.util.DiffUtil.runPreservingFocus(DiffUtil.java:710)
	at com.intellij.diff.impl.DiffRequestProcessor.doApplyRequest(DiffRequestProcessor.java:315)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$applyRequest$0(DiffRequestProcessor.java:297)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:170)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2425)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:217)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:169)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:161)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:167)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:63)
	at com.intellij.diff.impl.DiffRequestProcessor.applyRequest(DiffRequestProcessor.java:305)
	at com.intellij.diff.impl.DiffRequestProcessor.applyRequest(DiffRequestProcessor.java:284)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.lambda$null$0(CacheDiffRequestProcessor.java:114)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.finish(BackgroundTaskUtil.java:121)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.executeAndTryWait(BackgroundTaskUtil.java:109)
	at com.intellij.diff.util.DiffTaskQueue.executeAndTryWait(DiffTaskQueue.java:47)
	at com.intellij.diff.util.DiffTaskQueue.executeAndTryWait(DiffTaskQueue.java:38)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.updateRequest(CacheDiffRequestProcessor.java:109)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.updateRequest(CacheDiffRequestProcessor.java:88)
	at com.intellij.diff.impl.DiffRequestProcessor.updateRequest(DiffRequestProcessor.java:175)
	at com.intellij.diff.impl.DiffRequestProcessor.updateRequest(DiffRequestProcessor.java:170)
	at com.intellij.diff.impl.DiffWindowBase.lambda$init$1(DiffWindowBase.java:57)
	at com.intellij.openapi.ui.WindowWrapperBuilder$FrameWindowWrapper.show(WindowWrapperBuilder.java:288)
	at com.intellij.diff.impl.DiffWindowBase.show(DiffWindowBase.java:68)
	at com.intellij.diff.DiffManagerImpl.showDiffBuiltin(DiffManagerImpl.java:89)
	at com.intellij.diff.DiffManagerImpl.showDiff(DiffManagerImpl.java:66)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserBase.showDiff(ChangesBrowserBase.java:257)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserBase.onDoubleClick(ChangesBrowserBase.java:185)
	at com.intellij.openapi.vcs.changes.ui.ChangesTree$4.onDoubleClick(ChangesTree.java:204)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:395)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:461)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:460)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by sergio-castro** [comment]
Hi @getjack , do you know the steps to reproduce this so I can try to fix it?

**Comment by maunzCache** [comment]
Edit: Just happened to me again as https://kitchen.ci/ was running in the terminal.

No, sadly not. It happens randomly from my point of view during runtime. I can try to locate logs related to the issue. Did just happen today so there is a good change i can find something.

Update: Not much but something. I belive the issue origins from my *_.specs file.

Log
```
2019-08-20 09:13:06,477 [5409914]   WARN - j.openapi.wm.impl.IdeFrameImpl - Set preferredFocusableComponent in 'Local Changes' content in Version Control tool window to avoid focus-related problems. 
2019-08-20 09:13:06,477 [5409914]   WARN - j.openapi.wm.impl.IdeFrameImpl - Local Changes tool window - parent container is hidden 
2019-08-20 09:13:08,046 [5411483]   WARN - j.openapi.wm.impl.IdeFrameImpl - Set preferredFocusableComponent in 'null' content in Services tool window to avoid focus-related problems. 
2019-08-20 09:13:08,046 [5411483]   WARN - j.openapi.wm.impl.IdeFrameImpl - null tool window - parent container is hidden 
2019-08-20 09:13:12,064 [5415501]   INFO - rationStore.ComponentStoreImpl - Saving Project '/home/user/my_projects/ansible' my_projectsRunManager took 23 ms 
2019-08-20 09:13:12,109 [5415546]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 275 ms 
2019-08-20 09:13:23,626 [5427063]   INFO -  #git4idea.commands.GitHandler - [my-cli] git /usr/bin/git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune 
2019-08-20 09:13:23,626 [5427063]   INFO -  #git4idea.commands.GitHandler - [my-setup-modules] git /usr/bin/git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune 
2019-08-20 09:13:24,218 [5427655]   WARN - x.cache.CachedStatusCalculator - Hash mismatch between count and status: RevListCount[value=0,status=SUCCESS,top=<null>] ahead, RevListCount[value=0,status=SUCCESS,top=<null>] behind, status=SUCCESS <> RepoStatus[localHash=a31f6f69bdec4748e59a656baba819ceeeb305e7,localBranch=refs/heads/master,remote=RepoStatusRemote[remoteTrackingBranch=refs/remotes/origin/master,parentBranch=refs/remotes/origin/master,parentHash=a31f6f69bdec4748e59a656baba819ceeeb305e7]] 
2019-08-20 09:13:24,240 [5427677]   WARN - x.cache.CachedStatusCalculator - Hash mismatch between count and status: RevListCount[value=0,status=SUCCESS,top=<null>] ahead, RevListCount[value=0,status=SUCCESS,top=<null>] behind, status=SUCCESS <> RepoStatus[localHash=1c66039127e7868edc0d2fab4bb1f1a1a36104fd,localBranch=refs/heads/feature/MYPROJECT-1807,remote=RepoStatusRemote[remoteTrackingBranch=refs/remotes/origin/feature/MYPROJECT-1807,parentBranch=refs/remotes/origin/feature/MYPROJECT-1807,parentHash=1c66039127e7868edc0d2fab4bb1f1a1a36104fd]] 
2019-08-20 09:14:27,796 [5491233]   INFO - rationStore.ComponentStoreImpl - Saving Project '/home/user/my_projects/ansible' my_projectsProjectCodeStyleConfiguration took 20 ms, RunManager took 19 ms 
2019-08-20 09:14:27,797 [5491234]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 148 ms 
2019-08-20 09:14:55,506 [5518943]   INFO - rationStore.ComponentStoreImpl - Saving Project '/home/user/my_projects/ansible' my_projectsRunManager took 12 ms 
2019-08-20 09:14:55,507 [5518944]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 104 ms 
2019-08-20 09:14:57,631 [5521068]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 178 ms 
2019-08-20 09:17:48,812 [5692249]   WARN - com.intellij.util.xmlb.Binding - no accessors for class org.jetbrains.idea.perforce.perforce.ConnectionId 
2019-08-20 09:17:48,865 [5692302]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 191 ms 
2019-08-20 09:22:17,013 [5960450]   INFO - ittoolbox.blame.BlameCacheImpl - Annotated file:///home/user/my_projects/ansible/my-setup-modules/tasks/configure/my-saml-login.yml: BlameAnnotationImpl[file=file:///home/user/my_projects/ansible/my-setup-modules/tasks/configure/my-saml-login.yml,currentRevision=196b3f069c22b4bb622abcaf796503afc8ba6fe8] 
2019-08-20 09:22:39,295 [5982732]   INFO - rationStore.ComponentStoreImpl - Saving appUISettings took 11 ms, XDebuggerSettings took 15 ms 
2019-08-20 09:22:39,385 [5982822]   INFO - rationStore.ComponentStoreImpl - Saving Project '/home/user/my_projects/ansible' my_projectsProjectCodeStyleConfiguration took 19 ms, RunManager took 34 ms 
2019-08-20 09:22:39,441 [5982878]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 320 ms 
2019-08-20 09:23:20,842 [6024279]  ERROR - terminal.emulator.JediEmulator - Error processing OSC 1;..setup-modules 
2019-08-20 09:23:20,919 [6024356]  ERROR - terminal.emulator.JediEmulator - Unhandled Control sequence
parsed                        :ESC[?2004h
bytes read                    :ESC[ 
2019-08-20 09:23:37,906 [6041343]   INFO - ittoolbox.blame.BlameCacheImpl - Annotated file:///home/user/my_projects/ansible/my-setup-modules/test/integration/module-configuration/serverspec/my_module_spec.rb: BlameAnnotationImpl[file=file:///home/user/my_projects/ansible/my-setup-modules/test/integration/module-configuration/serverspec/my_module_spec.rb,currentRevision=c7e5ca11411f4b2bb1803c064b948d08520e139f]
2019-08-20 09:23:38,137 [6041574]  ERROR - ditor.colors.TextAttributesKey - TextAttributeKey(name:'OPERATOR', fallbackAttributeKey:'DEFAULT_CONSTANT')  was already registered with the other fallback attribute key: DEFAULT_BRACES 
java.lang.IllegalStateException: TextAttributeKey(name:'OPERATOR', fallbackAttributeKey:'DEFAULT_CONSTANT')  was already registered with the other fallback attribute key: DEFAULT_BRACES
	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:216)
	at com.intellij.openapi.editor.colors.TextAttributesKey.lambda$getOrCreate$4(TextAttributesKey.java:202)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932)
	at com.intellij.openapi.editor.colors.TextAttributesKey.getOrCreate(TextAttributesKey.java:202)
	at com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey(TextAttributesKey.java:189)
	at org.logtalk.intellij.editor.LogtalkSyntaxHighlighter.<clinit>(LogtalkSyntaxHighlighter.java:22)
	at org.logtalk.intellij.editor.LogtalkSyntaxHighlighterFactory.getSyntaxHighlighter(LogtalkSyntaxHighlighterFactory.java:15)
	at com.intellij.openapi.fileTypes.SyntaxHighlighterFactory.getSyntaxHighlighter(SyntaxHighlighterFactory.java:39)
	at org.jetbrains.plugins.ruby.ruby.lang.highlighter.RubyEditorHighlighter.<init>(RubyEditorHighlighter.java:45)
	at org.jetbrains.plugins.ruby.ruby.lang.highlighter.RubyEditorHighlighterProvider.getEditorHighlighter(RubyEditorHighlighterProvider.java:18)
	at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:78)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.loadEditorInBackground(TextEditorImpl.java:69)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.java:44)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$null$0(AsyncEditorLoader.java:88)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$scheduleLoading$1(AsyncEditorLoader.java:88)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:162)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$null$2(NonBlockingReadActionImpl.java:140)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:126)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$6(NonBlockingReadActionImpl.java:140)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Specs file:
```
require 'serverspec'
set :backend, :exec

describe file('/opt/my-module/conf/modules/my-module.my-service') do
  it { should exist }
  it { should be_directory }
  it { should be_owned_by 'user5' }
  it { should be_grouped_into 'user5' }
end

describe file('/opt/my-module/conf/modules/my-module.my-service/my-service.ini') do
  it { should exist }
  it { should be_file }
  it { should be_owned_by 'user5' }
  it { should be_grouped_into 'user5' }
end
```
